name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Lint and Format Check
        run: |
          pip install flake8
          flake8 .

      - name: Build Docker Image
        run: docker build -t my-app:latest .

      - name: Run Tests Inside Docker Container
        run: |
          docker run --rm -w /app my-app:latest python -m pytest

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t localhost:5000/my-app:latest .

      - name: Push to Local Docker Registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login localhost:5000 -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag my-app:latest localhost:5000/my-app:latest
          docker push localhost:5000/my-app:latest
